import { ColorOpacityHex } from '../utils/color-opacity-hex';
import { env } from '../utils/env';
import { storage } from '../utils/storage';

export const PRIMARY_COLOR = '#4a6dff';
export const SECONDARY_COLOR = '#6582fd';
export const ACTIVE_BG_COLOR = `${PRIMARY_COLOR}${ColorOpacityHex[0.1]}`;
export const INACTIVE_COLOR = '#303B4D';
export const YELLOW_WARNING = '#f5b234';
export const RED_BG = '#be1e3e';
export const RED_TEXT = '#f45777';
export const LIGHT_MODE_RED_COLOR = '#CE304F';
export const GREEN_BG = '#0fb797';
export const GREEN_TEXT = '#1cddb8';
export const YELLOW_BG = '#fadd90';
export const LIGHT_MODE_YELLOW_COLOR = '#F5B234';
export const WHITE_COLOR = '#fff';
export const LIVE_CHART_COLOR_DARK = '#96f4e5';
export const OFFLINE_CHART_COLOR_DARK = '#fce0ab';

export const LIVE_CHART_COLOR_LIGHT = '#12b798';
export const OFFLINE_CHART_COLOR_LIGHT = '#f5b234';
export const FONT_ONLINE_OFFLINE_LIGHT = '#ffffff';
export const BG_COLOR_DARK = '#1a2129';
export const BG_COLOR = '#1f252e';
export const BG_COLOR_LIGHT = '#f3f5f9';

export const INPUT_FOCUS_COLOR = `${SECONDARY_COLOR}${ColorOpacityHex[0.6]}`;
export const QR_BUTTON_COLOR = `${SECONDARY_COLOR}${ColorOpacityHex[0.3]}`;

export const BUTTON_HOVER_COLOR = '#4a51ff';
export const TABLE_ROW_HOVER = `#8f9eb5${ColorOpacityHex[0.1]}`;
export const TABLE_ROW_HOVER_DARK = `#8f9eb5${ColorOpacityHex[0.1]}`;
export const SECONDARY_TEXT_COLOR = '#8f9eb5';
export const SECONDARY_TEXT_COLOR_DARK = `${SECONDARY_TEXT_COLOR}${ColorOpacityHex[0.6]}`;
export const SECONDARY_TEXT_COLOR_DARKER = `${SECONDARY_TEXT_COLOR}${ColorOpacityHex[0.4]}`;
export const DEFAULT_FONT_COLOR = '#ccd9dd';

export const MODAL_BG_COLOR = BG_COLOR;
export const CARD_BG_COLOR = BG_COLOR_DARK;

export const HEADER_BG_COLOR = '#1a2129';

export const TOOLTIP_BG_COLOR_LIGHT = '#f0f4fb';
export const TOOLTIP_BG_COLOR_DARK = '#2c343e';

export const BTN_HINT_HOVER = '#385bed';
export const MY_BALANCE_BG = '#252c36';

const common = {
	SECONDARY_COLOR,
	PRIMARY_COLOR,
	ACTIVE_BG_COLOR,
	HEADER_BG_COLOR,
	widgetContainerTitleColor: SECONDARY_TEXT_COLOR,
	type: 'dark',
	bgColorDark: BG_COLOR_DARK,
	bgColor: BG_COLOR,
	sideBg: '#131a22',
	widgetContainerBg: '#131a22',
	containerBg: BG_COLOR,
	chooseMarketBg: `${SECONDARY_TEXT_COLOR}${ColorOpacityHex[0.08]}`,
	textSuccessColor: GREEN_TEXT,
	textDangerColor: RED_TEXT,
	rightAsideBG: CARD_BG_COLOR,
	INACTIVE_COLOR,
	WRAPPER_BG_COLOR: `#8f9eb5${ColorOpacityHex[0.1]}`,
	PROGRESS_BAR_BG_COLOR: '#242C36',
	TAB_BG_COLOR: `${SECONDARY_TEXT_COLOR}${ColorOpacityHex[0.08]}`,
	WHITER_TEXT_COLOR: '#fff',
	emptyCardBgColor: BG_COLOR_DARK,
	loadingCardBgColor: BG_COLOR,
	TAB_BORDER_COLOR: `${SECONDARY_TEXT_COLOR}${ColorOpacityHex[0.18]}`,

	// COLORS
	RED_BG,
	RED_TEXT,
	GREEN_BG,
	GREEN_TEXT,
	YELLOW_BG,
	CARD_BG_COLOR,
	NOT_VERIFIED_CARD_BG: `#fffad5${ColorOpacityHex[0.08]}`,
	// MODAL_BG_COLOR: MODAL_BG_COLOR,
	INFO_BG_COLOR: `${SECONDARY_COLOR}${ColorOpacityHex[0.08]}`,
	WARNING_INFO_BG_COLOR: `#fadd90${ColorOpacityHex[0.06]}`,
	WARNING_REDEEM_BG_COLOR: `#e8c19b${ColorOpacityHex[0.06]}`,
	SECONDARY_TEXT_COLOR,
	SECONDARY_TEXT_COLOR_DARK,
	SECONDARY_TEXT_COLOR_DARKER,
	SECONDARY_TEXT_COLOR_DARKEST: SECONDARY_TEXT_COLOR_DARKER,
	DISABLED_COLOR: `#8f9eb5${ColorOpacityHex[0.2]}`,
	WARNING_MODAL_TOP_PANEL_BG: `${RED_BG}${ColorOpacityHex[0.7]}`,
	WARNING_MODAL_TEXT: '#ffe6eb',
	WHITE_COLOR,
	WHITE_BG: WHITE_COLOR,
	WHITE_FONT_BG: '#ccd9dd',

	// BTN
	BTN_COLOR: '#fff',
	BTN_BG_COLOR: PRIMARY_COLOR,

	BTN_BG_COLOR_ACTIVE: BUTTON_HOVER_COLOR,
	BTN_TEXT_COLOR_DISABLED: `#8f9eb5${ColorOpacityHex[0.3]}`,
	BTN_NORMAL_COLOR: SECONDARY_COLOR,
	BTN_NORMAL_COLOR_ACTIVE: '#fff',
	BTN_NORMAL_BG_COLOR: `${SECONDARY_COLOR}${ColorOpacityHex[0.14]}`,
	BTN_NORMAL_BG_COLOR_ACTIVE: SECONDARY_COLOR,
	BTN_HOVER_COLOR: BUTTON_HOVER_COLOR,
	BTN_BORDER_RADIUS: '24px',
	BTN_DISABLED_BG_COLOR: `#8f9eb5${ColorOpacityHex[0.1]}`,
	BTN_HINT_HOVER,

	// SCROLL
	SCROLL_BG_COLOR: '#445169',

	// Table
	TABLE_HEADER_BG_COLOR: 'rgb(32, 40, 50)',
	TABLE_HEADER_COLOR: `#8f9eb5${ColorOpacityHex[0.6]}`,
	TABLE_BORDER_COLOR: `${SECONDARY_TEXT_COLOR}${ColorOpacityHex[0.1]}`,
	TABLE_ROW_HOVER,
	TABLE_ROW_HOVER_DARK,

	// FONT
	DEFAULT_FONT: 'Ubuntu, "Helvetica Neue GEO", "Helvetica Neue GEO Caps", sans-serif',
	DEFAULT_FONT_SIZE: '1rem',
	DEFAULT_LINE_HEIGHT: '1.125rem',
	DEFAULT_FONT_COLOR,
	DEFAULT_FONT_COLOR_SECONDARY: DEFAULT_FONT_COLOR,
	SECONDARY_FONT: 'Ubuntu, "Helvetica Neue GEO Caps", "Helvetica Neue GEO", sans-serif',
	SECONDARY_FONT_COLOR: '#8f9eb5',
	SECONDARY_LABEL_COLOR: `#8f9eb5${ColorOpacityHex[0.8]}`,

	// INPUT
	INPUT_HEIGHT: '45px',
	INPUT_HEIGHT_MOBILE: '46px',
	INPUT_BG_COLOR: 'transparent',
	INPUT_LABEL_COLOR: `${SECONDARY_TEXT_COLOR}${ColorOpacityHex[0.6]}`,
	INPUT_BORDER_COLOR: '#303b4d',
	INPUT_ABSOLUTE_COMP_BORDER_COLOR: '#303b4d',
	INPUT_BORDER_COLOR_FOCUSED: INPUT_FOCUS_COLOR,
	INPUT_BORDER_RADIUS: '6px',
	INPUT_TRANSITION: 'all 0.2',
	INPUT_LETTER_SPACING: '1px',
	INPUT_PLACEHOLDER_COLOR: `${SECONDARY_TEXT_COLOR}${ColorOpacityHex[0.4]}`,

	INPUT_DISABLED_OPACITY: '.4',
	INPUT_DISABLED_BORDER_COLOR: `#303b4d${ColorOpacityHex[0.6]}`,
	INPUT_DISABLED_COLOR: `#8f9eb5${ColorOpacityHex[0.2]}`,
	INPUT_ERROR_BORDER_COLOR: `${RED_TEXT}${ColorOpacityHex[0.8]}`,
	INPUT_ERROR_BACKGROUND_COLOR: 'transparent',
	INPUT_FONT: 'Ubuntu, "Helvetica Neue GEO", "Helvetica Neue GEO Caps", sans-serif',
	INPUT_FONT_SIZE: '0.875rem',
	INPUT_LINE_HEIGHT: '1rem',
	INPUT_CHECKBOX_BACKGROUND: `${SECONDARY_TEXT_COLOR}${ColorOpacityHex[0.15]}`,
	INPUT_CHECKBOX_CIRCLE_BACKGROUND: '#535e6d',
	INPUT_SEARCH_DARK_PLACEHOLDER_COLOR: `#8f9eb5${ColorOpacityHex[0.25]}`,
	FORM_ERROR_BG_COLOR: `#f45777${ColorOpacityHex[0.08]}`,
	DATEPICKER_DAY_DISABLED: `#8f9eb5${ColorOpacityHex[0.25]}`,
	DATEPICKER_DROPDOWN_BG: '#111a23',
	DATEPICKER_DROPDOWN_BORDER_COLOR: INACTIVE_COLOR,

	// SVG
	SVG_FILL: '#8f9eb5',
	SVG_FILL_SECONDARY: '#8f9eb5',
	SVG_FILL_LIGHT: '#647082',
	SVG_FILL_WARNING: '#fadd90',
	SVG_RECT_FILL: `#8f9eb5${ColorOpacityHex[0.08]}`,
	SVG_RECT_WARNING_FILL: `#8f9eb5${ColorOpacityHex[0.08]}`,
	LIGHT_SVG_FILL: '#fcfcff',
	SVG_FILL_ACTIVE: SECONDARY_COLOR,
	ASSET_URL: env.ASSET_URL,
	SVG_STROKE_COLIR: '#232a34',
	SVG_RECT_STROKE_COLOR: `#ccd9dd${ColorOpacityHex[0.15]}`,

	// DROPDOWN
	DROPDOWN_DEFAULT_BOX_SHADOW: 'none',
	DROPDOWN_INNER_TEXT_COLOR: '#ccd9dd',
	DROPDOWN_BG_COLOR: '#2c343e',
	DROPDOWN_SECONDARY_BOX_SHADOW: 'none',
	DROPDOWN_FOCUSED_SVG_FILL: '#ccd9dd',
	SELECT_PLACEHOLDER_COLOR: '#8f9eb5',

	TOOLTIP_BG_COLOR: TOOLTIP_BG_COLOR_DARK,
	MODAL_TITLE_FONT_SIZE: '26px',
	MODAL_BACKDROP_BG_COLOR: `#070c12${ColorOpacityHex[0.4]}`,
	TEST_COLOR: BG_COLOR_DARK,

	SEPARATOR_COLOR: `#8f9eb5${ColorOpacityHex[0.14]}`,
	DROPDOWN_OPEN_SEPARATOR_COLOR: `#303b4d${ColorOpacityHex[0.6]}`,

	// LOADINGS
	CONTENT_LOADER_PRIMARY_COLOR: '#2B323C',
	CONTENT_LOADER_SECONDARY_COLOR: '#454D57',

	// FONT_WEIGHTS
	FONT_WEIGTH_NORMAL_TO_MEDIUM: '400',
	FONT_WEIGHT_MEDIUM_TO_BOLD: '500',

	// CARDLESS
	BANNER_DARK: TOOLTIP_BG_COLOR_DARK,
	FILTER_BUTTON_BG: '#6582fd24',
	FILTER_BUTTON_HOVER: '#4a51ff',
	HEADER_BG_COLOR_DARK: '#161D26',
	REFERALS_SEPARATOR: '#8f9eb52E',
	NOTE_BG_COLOR: '#8f9eb514',
	NOTE_TEXT: '#8f9eb599',
	UNVERIFIED_WALLET_CARD_BG: '#fadd901A',
	WARNING_RED_TEXT: '#f45777',
	FEE_MODAL_TEXT_COLOR: '#CCD9DD',
	IMPORTANT_MODAL_INFO_TOP_PANEL_BG: '#8e2039',
	IMPORTANT_MODAL_CONTENT_PANEL_BG: '#1f252e',
	IMPORTANT_MODAL_INFO_CONTENT_TEXT: '#ffe6eb',
	IMPORTANT_MODAL_INFO_CONTENT_TEXT_RED: '#ffa0b3',
	IMPORTANT_MODAL_AGREEMENT_TEXT: '#ffe6eb',
	TAB_TAG_BG: `#8f9eb5${ColorOpacityHex[0.08]}`,
	TEXT_HOVER_BG: `#8f9eb5${ColorOpacityHex[0.01]}`,
	TEXT_HOVER: '#fff',
	bgColor_mobile: BG_COLOR,
	HEADER_BG_COLOR_mobile: BG_COLOR,
	MODAL_BG_COLOR: BG_COLOR,
	INPUT_LABEL_BG_COLOR: CARD_BG_COLOR,

	SVG_FILL_WHITE: '#ccd9dd',
	RC_SLIDER_STEP_BG_COLOR: `#8f9eb5${ColorOpacityHex[0.2]}`,
	CRYPTOMAT_BANNER_PRIMARY_COLOR: '#5adcff',
	ADDITIONAL_INFO_BG: `${SECONDARY_TEXT_COLOR}${ColorOpacityHex[0.04]}`,

	ACTIVE_TAB_COLOR: PRIMARY_COLOR,
	SUBTITLE_COLOR: `#8f9eb5${ColorOpacityHex[0.6]}`,
	PROFILE_SECONDARY_LABEL_COLOR: `#8f9eb5${ColorOpacityHex[0.8]}`,
	PROFILE_STATUS_SQUARE_BG_COLOR: `#ccd9dd${ColorOpacityHex[0.8]}`,
	ADDITIONAL_TEXT_COLOR: `#8f9eb5${ColorOpacityHex[0.6]}`,
	STAKE_ADDED_MOBILE: '#7fd1c1',

	TABLE_HEADER_DARK_LAYER: '#202832',

	// Referral
	REFERRAL_PROGRESS_BAR_TRAIL_COLOR: `#8f9eb5${ColorOpacityHex[0.1]}`,
	REFERRAL_LABEL_COLOR: `#8f9eb5${ColorOpacityHex[0.8]}`,

	DATA_TABLE_BG_COLOR: `#8f9eb5${ColorOpacityHex[0.08]}`,
	REFERRAL_COUNTDOWN_SECONDARY_COLOR: SECONDARY_TEXT_COLOR,
	REFERRAL_QR_CODE_BG: '#18212e',

	// Toast - Cookie
	TOAST_BG_COLOR: '#303b4d',
	TOAST_SECONDARY_TEXT_COLOR: '#8f9eb5',
	TOAST_BOX_SHADOW: '0 32px 14px 0 rgba(17, 25, 34, 0.16)',
	COOKIE_BOX_SHADOW: 'none',
	COOKIE_SECONDARY_TEXT_COLOR: '#8f9eb5',

	// ORDER BOOK
	ORDER_BOOK_BID_CHART_BG_IMAGE: 'linear-gradient(to left, rgba(27, 33, 40, 0.2) -1%, rgba(15, 183, 151, 0.08) 99%)',
	ORDER_BOOK_BID_BORDER_BOTTOM_COLOR: 'rgba(15, 183, 151, 0.5)',
	ORDER_BOOK_BID_ROW_BG_COLOR: 'none',
	ORDER_BOOK_ASK_CHART_BG_IMAGE: 'linear-gradient(to left, rgba(244, 87, 119, 0.08) -5%, rgba(27, 33, 40, 0.08) 121%)',
	ORDER_BOOK_ASK_BORDER_BOTTOM_COLOR: 'rgba(244, 87, 119, 0.5)',
	ORDER_BOOK_ASK_ROW_BG_COLOR: 'none',

	// SVG
	SECURITY_ICON_FILL: `#8f9eb5${ColorOpacityHex[0.6]}`,
	SECURITY_ICON_FILL_MOBILE: '#8f9eb5',

	TRANSACTION_DETAILS_BOTTOM_INFO_BG: `#8f9eb5${ColorOpacityHex[0.08]}`,

	BTN_QR_COLOR: `${WHITE_COLOR}`,
	BTN_QR_BORDER_COLOR: `#ffffff${ColorOpacityHex[0.3]}`,
	TEXT_QR_COLOR: '#c0cbdd',
	SECONDARY_CARD_BG: `#8f9eb5${ColorOpacityHex[0.06]}`,
	VERIFICATION_DOT_BORDER: '#282e38',
	HEADER_PROFILE_ICON: 'rgb(204, 217, 221)',
	PROFILE_DROPDOWN_SVG_ACTIVE: 'white',
	PROFILE_ROUND_ICONS_FILL: '#ccd9dd',

	TO_COIN_MODAL_TITLE: '#ffffff',
	TO_COIN_MODAL_DESCRIPTION: '#ccd9dd',
	CHART_LOADING_BACKGROUND: '#1a2129',
	MY_BALANCE_BG
};

// Light
export const SECONDARY_TEXT_COLOR_NIGHT = `${BG_COLOR_DARK}${ColorOpacityHex[0.6]}`;
const light = {
	CHART_LOADING_BACKGROUND: '#fff',

	TO_COIN_MODAL_TITLE: '#1a2129',
	TO_COIN_MODAL_DESCRIPTION: '#1a212999',

	PROFILE_ROUND_ICONS_FILL: '#1a2129',
	PROFILE_DROPDOWN_SVG_ACTIVE: '#1a2129',
	HEADER_PROFILE_ICON: '#1a2129CC',
	VERIFICATION_DOT_BORDER: '#f6f7f9',
	widgetContainerBg: '#f3f5f9',
	widgetContainerTitleColor: BG_COLOR_DARK,
	HEADER_BG_COLOR: WHITE_COLOR,
	CARD_BG_COLOR: WHITE_COLOR,
	chooseMarketBg: '#f3f5f9',
	WHITER_TEXT_COLOR: BG_COLOR_DARK,
	bgColor: BG_COLOR_LIGHT,
	RED_TEXT: LIGHT_MODE_RED_COLOR,
	containerBg: '#F3F5F9',
	emptyCardBgColor: WHITE_COLOR,
	TEST_COLOR: '#f3f5f9',
	loadingCardBgColor: WHITE_COLOR,
	ADDITIONAL_INFO_BG: `${SECONDARY_TEXT_COLOR}${ColorOpacityHex[0.1]}`,
	TAB_TAG_BG: `#C0CBDD${ColorOpacityHex[0.3]}`,
	TEXT_HOVER_BG: `#c0cbdd${ColorOpacityHex[0.3]}`,
	TEXT_HOVER: '#1a2129',
	bgColor_mobile: '#fff',
	HEADER_BG_COLOR_mobile: '#fff',
	SVG_FILL_WHITE: BG_COLOR_DARK,

	INPUT_LABEL_BG_COLOR: '#fff',
	SUBTITLE_COLOR: '#8f9eb5',
	ACTIVE_TAB_COLOR: SECONDARY_COLOR,
	// Input
	INPUT_BORDER_COLOR: `${SECONDARY_TEXT_COLOR}${ColorOpacityHex[0.8]} `,
	INPUT_BORDER_COLOR_FOCUSED: `#4a6dff${ColorOpacityHex[0.8]}`,
	INPUT_PLACEHOLDER_COLOR: `${SECONDARY_TEXT_COLOR}${ColorOpacityHex[0.5]}`,
	INPUT_ERROR_BORDER_COLOR: `${LIGHT_MODE_RED_COLOR}${ColorOpacityHex[0.8]}`,
	INPUT_CHECKBOX_BACKGROUND: `${SECONDARY_TEXT_COLOR}${ColorOpacityHex[0.2]}`,
	INPUT_DISABLED_COLOR: `#1a2129${ColorOpacityHex[0.2]}`,
	INPUT_DISABLED_BORDER_COLOR: `#8f9eb5${ColorOpacityHex[0.2]}`,
	INPUT_CHECKBOX_CIRCLE_BACKGROUND: SECONDARY_TEXT_COLOR,
	INPUT_LABEL_COLOR: `#1a2129${ColorOpacityHex[0.4]}`,
	INPUT_SEARCH_DARK_PLACEHOLDER_COLOR: `#1a2129${ColorOpacityHex[0.2]}`,
	INPUT_ABSOLUTE_COMP_BORDER_COLOR: `#8f9eb5${ColorOpacityHex[0.24]}`,
	FORM_ERROR_BG_COLOR: `#ce304f${ColorOpacityHex[0.1]}`,

	// Select
	SELECT_PLACEHOLDER_COLOR: `#1a2129${ColorOpacityHex[0.4]}`,

	// BTN
	BTN_NORMAL_COLOR: '#4a6dff',
	BTN_NORMAL_BG_COLOR: `${PRIMARY_COLOR}${ColorOpacityHex[0.16]}`,
	BTN_TEXT_COLOR_DISABLED: `#8f9eb5${ColorOpacityHex[0.5]}`,
	BTN_DISABLED_BG_COLOR: `#8f9eb5${ColorOpacityHex[0.2]}`,

	BTN_QR_COLOR: `${PRIMARY_COLOR}`,
	BTN_QR_BORDER_COLOR: `${PRIMARY_COLOR}`,
	TEXT_QR_COLOR: `${BG_COLOR_DARK}`,

	// Tab
	TAB_BG_COLOR: `${SECONDARY_TEXT_COLOR}${ColorOpacityHex[0.16]}`,

	// Table
	TABLE_HEADER_BG_COLOR: '#F1F4F8',
	TABLE_HEADER_COLOR: `#1a2129${ColorOpacityHex[0.4]}`,
	TABLE_HEADER_DARK_LAYER: 'transparent',
	TABLE_ROW_HOVER: `#c0cbdd${ColorOpacityHex[0.3]}`,
	TABLE_ROW_HOVER_DARK,
	TABLE_BORDER_COLOR: `${SECONDARY_TEXT_COLOR}${ColorOpacityHex[0.24]}`,

	// Dropdown
	DROPDOWN_BG_COLOR: WHITE_COLOR,
	DROPDOWN_DEFAULT_BOX_SHADOW: '0 10px 26px 0 rgba(77, 91, 114, 0.16);',
	DROPDOWN_SECONDARY_BOX_SHADOW: '0 10px 24px 0 rgba(155, 169, 185, 0.25)',

	DROPDOWN_INNER_TEXT_COLOR: `#1a2129${ColorOpacityHex[0.8]}`,
	DROPDOWN_FOCUSED_SVG_FILL: '#8f9eb5',

	TOOLTIP_BG_COLOR: TOOLTIP_BG_COLOR_LIGHT,

	// Modal

	MODAL_BG_COLOR: WHITE_COLOR,
	MODAL_BACKDROP_BG_COLOR: `#0a121c${ColorOpacityHex[0.55]}`,

	// Progress Bar
	PROGRESS_BAR_BG_COLOR: `${SECONDARY_TEXT_COLOR}${ColorOpacityHex[0.18]}`,
	RC_SLIDER_STEP_BG_COLOR: `#8f9eb5${ColorOpacityHex[0.18]}`,

	// WidgetContainers
	TAB_BORDER_COLOR: `${SECONDARY_TEXT_COLOR}${ColorOpacityHex[0.24]}`,

	// Scroll
	SCROLL_BG_COLOR: '#dee1e6',

	DEFAULT_FONT_COLOR: BG_COLOR_DARK,
	SECONDARY_TEXT_COLOR: SECONDARY_TEXT_COLOR_NIGHT,
	SECONDARY_TEXT_COLOR_DARK: SECONDARY_TEXT_COLOR_NIGHT,
	RED_BG: LIGHT_MODE_RED_COLOR,

	SVG_FILL: `#1a2129${ColorOpacityHex[0.8]}`,
	SVG_FILL_LIGHT: `#1a2129${ColorOpacityHex[0.8]}`,
	SVG_FILL_SECONDARY: `#1a2129${ColorOpacityHex[0.6]}`,
	SVG_RECT_FILL: `#C0CBDD${ColorOpacityHex[0.3]}`,
	SVG_STROKE_COLIR: '#edeff3',
	SVG_FILL_WARNING: '#f5b234',
	SVG_RECT_WARNING_FILL: `#f7b73f${ColorOpacityHex[0.16]}`,
	SVG_RECT_STROKE_COLOR: `#8f9eb5${ColorOpacityHex[0.4]}`,

	DEFAULT_FONT_COLOR_SECONDARY: SECONDARY_TEXT_COLOR_NIGHT,
	ACTIVE_BG_COLOR: `${SECONDARY_COLOR}${ColorOpacityHex[0.16]}`,
	SECONDARY_COLOR: PRIMARY_COLOR,
	SECONDARY_FONT_COLOR: '#303b4d',
	PRIMARY_COLOR: SECONDARY_COLOR,
	WHITE_COLOR: `${BG_COLOR_DARK}${ColorOpacityHex[0.8]}`,
	WHITE_BG: '#1a2129',
	WHITE_FONT_BG: '#1a2129',
	SEPARATOR_COLOR: `#8f9eb5${ColorOpacityHex[0.24]}`,
	DROPDOWN_OPEN_SEPARATOR_COLOR: `#8f9eb5${ColorOpacityHex[0.24]}`,

	SECONDARY_TEXT_COLOR_DARKER: SECONDARY_TEXT_COLOR_NIGHT,
	SECONDARY_TEXT_COLOR_DARKEST: SECONDARY_TEXT_COLOR_NIGHT,
	DISABLED_COLOR: `#8f9eb5${ColorOpacityHex[0.2]}`,

	LIGHT_SVG_FILL: BG_COLOR_DARK,
	YELLOW_BG: LIGHT_MODE_YELLOW_COLOR,
	INFO_BG_COLOR: `${SECONDARY_COLOR}${ColorOpacityHex[0.1]}`,
	WARNING_INFO_BG_COLOR: `${LIGHT_MODE_YELLOW_COLOR}${ColorOpacityHex[0.1]}`,

	// ORDER_BOOK
	ORDER_BOOK_BID_CHART_BG_IMAGE: 'none',
	ORDER_BOOK_BID_BORDER_BOTTOM_COLOR: `${GREEN_BG}${ColorOpacityHex[0.5]}`,
	ORDER_BOOK_BID_ROW_BG_COLOR: `${GREEN_BG}${ColorOpacityHex[0.1]}`,
	ORDER_BOOK_ASK_CHART_BG_IMAGE: 'none',
	ORDER_BOOK_ASK_BORDER_BOTTOM_COLOR: `#f45777${ColorOpacityHex[0.5]}`,
	ORDER_BOOK_ASK_ROW_BG_COLOR: `${LIGHT_MODE_RED_COLOR}${ColorOpacityHex[0.1]}`,

	// LOADINGS
	CONTENT_LOADER_PRIMARY_COLOR: `#8F9EB5${ColorOpacityHex[0.26]}`,
	CONTENT_LOADER_SECONDARY_COLOR: '#EFF5FF',

	// FONT WEIGHTS
	FONT_WEIGTH_NORMAL_TO_MEDIUM: '500',
	FONT_WEIGHT_MEDIUM_TO_BOLD: '700',

	DATEPICKER_DAY_DISABLED: `#8f9eb5${ColorOpacityHex[0.6]}`,
	DATEPICKER_DROPDOWN_BG: '#fff',
	DATEPICKER_DROPDOWN_BORDER_COLOR: `#8f9eb5${ColorOpacityHex[0.4]}`,

	REFERRAL_LABEL_COLOR: `#1a2129${ColorOpacityHex[0.4]}`,
	DATA_TABLE_BG_COLOR: '#f3f5f9',
	REFERRAL_COUNTDOWN_SECONDARY_COLOR: `${SECONDARY_TEXT_COLOR}${ColorOpacityHex[0.8]}`,
	CRYPTOMAT_BANNER_PRIMARY_COLOR: '#0ecbfd',
	REFERRAL_PROGRESS_BAR_TRAIL_COLOR: `#d3dee8${ColorOpacityHex[0.28]}`,
	REFERRAL_QR_CODE_BG: '#dae3f7',
	TOAST_BG_COLOR: WHITE_COLOR,
	TOAST_BOX_SHADOW: '0 10px 24px 0 rgba(155, 169, 185, 0.35)',
	GREEN_TEXT: GREEN_BG,
	COOKIE_BOX_SHADOW: '0 10px 24px 0 rgba(155, 169, 185, 0.45)',
	COOKIE_SECONDARY_TEXT_COLOR: `#303b4d${ColorOpacityHex[0.4]}`,
	WRAPPER_BG_COLOR: '#F3F5F9',

	PROFILE_SECONDARY_LABEL_COLOR: `#1a2129${ColorOpacityHex[0.6]}`,
	PROFILE_STATUS_SQUARE_BG_COLOR: `#1a2129${ColorOpacityHex[0.6]}`,
	TOAST_SECONDARY_TEXT_COLOR: `#1a2129${ColorOpacityHex[0.4]}`,
	ADDITIONAL_TEXT_COLOR: `#1a2129${ColorOpacityHex[0.4]}`,
	SECONDARY_CARD_BG: `#c0cbdd${ColorOpacityHex[0.22]}`,
	// Banner Popup
	BANNER_DARK: WHITE_COLOR,

	// SVG
	SECURITY_ICON_FILL: '#8f9eb5',
	SECURITY_ICON_FILL_MOBILE: ''
};

export const themes = {
	dark: common,
	light: { ...common, ...light }
};

export type Theme = (typeof themes)['dark'];
export type ThemeMode = 'light' | 'dark';

export const defaultTheme = (storage('theme').get() as ThemeMode) ?? 'dark';

export const FULL_SCREEN_LOADING_BG = defaultTheme === 'light' ? themes.light.CARD_BG_COLOR : themes.dark.CARD_BG_COLOR;
